name: Build
#workflowun ne zaman calisacagini goster
on:
  push:
    branches:
      #main branchine bir sey pushlanacagi zaman assagisindaki jobu otomatik olarak hallet
      #bunun cok fazla cesiti var pr acildiginda release acildiginda gibi durumlar icinde yazabilirsin sadecde push icin degil yani
      - main


env:
  REGISTRY: ghcr.io #github container registry k8s gibi ortamlara deploy icin gerekli olan seyleri saglar ghrc.io
  REPO_OWNER: ${{ github.repository_owner }}


jobs:
  build:
    strategy:
      matrix:
        image_name: ["order","shipping","inventory"]
    runs-on: ubuntu-latest
    steps:
      #birinci adim checkout etme,yapilmasi gereken ilk adimdir yoksa elimizde bir git projesi olmayacaktir
      - name: Checkout
        uses: actions/checkout@v2 #hazir bir sey kullaninca uses calistirman gereken bir komut icin run komutunu kullan

      - name: Setup Java
        uses: actions/setup-java@v3
        with: #eger actionlar desteklerse actionlara with ile paramaetre verebilirsin
          java-version: 21
          distribution: "corretto" #amazon java dagitimi

      - name: Build
        working-directory: ${{ matrix.image_name }}
        run: |
          ./gradlew bootJar
          mv build/libs/$(ls build/libs | head -1) app.jar  #uygulamanin jar dosyasini rename ediyor

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}


      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: 'true'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets:
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}






